# Generated by Django 5.1 on 2024-08-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
        ),
    ]
